# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Post.create(name: '	J. K. Rowling	', title: '	The Philosopher\'s Stone (1997)	', body: '	"The Dursleys were so mean that hideous that summer that all Harry Potter wanted was to get back to the Hogwarts School for Witchcraft and Wizardry. But just as he\'s packing his bags, Harry receives a warning from a strange, impish creature named Dobby who says that if Harry Potter returns to Hogwarts, disaster will strike.

And strike it does. For in Harry\'s second year at Hogwarts, fresh torments and horrors arise, including an outrageously stuck-up new professor, Gilderoy Lockheart, a spirit named Moaning Myrtle who haunts the girls\' bathroom, and the unwanted attentions of Ron Weasley\'s younger sister, Ginny.

But each of these seem minor annoyances when the real trouble begins, and someone--or something--starts turning Hogwarts students to stone. Could it be Draco Malfoy, a more poisonous rival than ever? Could it possibly be Hagrid, whose mysterious past is finally told? Or could it be the one everyone at Hogwarts most suspects...Harry Potter himself?"	', created_at: '	2017-06-20 13:01:00 UTC	', updated_at: '	2017-06-20 13:01:00 UTC	')
Post.create(name: '	J. K. Rowling	', title: '	The Chamber of Secrets (1998)	', body: '	"The Dursleys were so mean that hideous that summer that all Harry Potter wanted was to get back to the Hogwarts School for Witchcraft and Wizardry. But just as he\'s packing his bags, Harry receives a warning from a strange, impish creature named Dobby who says that if Harry Potter returns to Hogwarts, disaster will strike.

And strike it does. For in Harry\'s second year at Hogwarts, fresh torments and horrors arise, including an outrageously stuck-up new professor, Gilderoy Lockheart, a spirit named Moaning Myrtle who haunts the girls\' bathroom, and the unwanted attentions of Ron Weasley\'s younger sister, Ginny.

But each of these seem minor annoyances when the real trouble begins, and someone--or something--starts turning Hogwarts students to stone. Could it be Draco Malfoy, a more poisonous rival than ever? Could it possibly be Hagrid, whose mysterious past is finally told? Or could it be the one everyone at Hogwarts most suspects...Harry Potter himself?"	', created_at: '	2017-06-20 13:02:00 UTC	', updated_at: '	2017-06-20 13:02:00 UTC	')
Post.create(name: '	J. K. Rowling	', title: '	The Prisoner of Azkaban (1999)	', body: '	"For twelve long years, the dread fortress of Azkaban held an infamous prisoner named Sirius Black. Convicted of killing thirteen people with a single curse, he was said to be the heir apparent to the Dark Lord, Voldemort.

Now he has escaped, leaving only two clues as to where he might be headed: Harry Potter\'s defeat of You-Know-Who was Black\'s downfall as well. And the Azkban guards heard Black muttering in his sleep, ""He\'s at Hogwarts...he\'s at Hogwarts.""

Harry Potter isn\'t safe, not even within the walls of his magical school, surrounded by his friends. Because on top of it all, there may well be a traitor in their midst."	', created_at: '	2017-06-20 13:03:00 UTC	', updated_at: '	2017-06-20 13:03:00 UTC	')
Post.create(name: '	J. K. Rowling	', title: '	The Goblet of Fire (2000)	', body: '	Harry Potter is midway through his training as a wizard and his coming of age. Harry wants to get away from the pernicious Dursleys and go to the International Quidditch Cup. He wants to find out about the mysterious event that\'s supposed to take place at Hogwarts this year, an event involving two other rival schools of magic, and a competition that hasn\'t happened for a hundred years. He wants to be a normal, fourteen-year-old wizard. But unfortunately for Harry Potter, he\'s not normal - even by wizarding standards. And in his case, different can be deadly.	', created_at: '	2017-06-20 13:04:00 UTC	', updated_at: '	2017-06-20 13:04:00 UTC	')
Post.create(name: '	J. K. Rowling	', title: '	The Order of the Phoenix (2003)	', body: '	In his fifth year at Hogwart\'s, Harry faces challenges at every turn, from the dark threat of He-Who-Must-Not-Be-Named and the unreliability of the government of the magical world to the rise of Ron Weasley as the keeper of the Gryffindor Quidditch Team. Along the way he learns about the strength of his friends, the fierceness of his enemies, and the meaning of sacrifice.	', created_at: '	2017-06-20 13:05:00 UTC	', updated_at: '	2017-06-20 13:05:00 UTC	')
Post.create(name: '	J. K. Rowling	', title: '	The Half-Blood Prince (2005)	', body: '	"The war against Voldemort is not going well; even the Muggles have been affected. Dumbledore is absent from Hogwarts for long stretches of time, and the Order of the Phoenix has already suffered losses. 

And yet . . . as with all wars, life goes on. Sixth-year students learn to Apparate. Teenagers flirt and fight and fall in love. Harry receives some extraordinary help in Potions from the mysterious Half-Blood Prince. And with Dumbledore\'s guidance, he seeks out the full, complex story of the boy who became Lord Voldemort -- and thus finds what may be his only vulnerability."	', created_at: '	2017-06-20 13:06:00 UTC	', updated_at: '	2017-06-20 13:06:00 UTC	')
Post.create(name: '	J. K. Rowling	', title: '	The Deathly Hallows (2007)	', body: '	"Readers beware. The brilliant, breathtaking conclusion to J.K. Rowling\'s spellbinding series is not for the faint of heart--such revelations, battles, and betrayals await in Harry Potter and the Deathly Hallows that no fan will make it to the end unscathed. Luckily, Rowling has prepped loyal readers for the end of her series by doling out increasingly dark and dangerous tales of magic and mystery, shot through with lessons about honor and contempt, love and loss, and right and wrong. Fear not, you will find no spoilers in our review--to tell the plot would ruin the journey, and Harry Potter and the Deathly Hallows is an odyssey the likes of which Rowling\'s fans have not yet seen, and are not likely to forget. But we would be remiss if we did not offer one small suggestion before you embark on your final adventure with Harry--bring plenty of tissues.
The heart of Book 7 is a hero\'s mission--not just in Harry\'s quest for the Horcruxes, but in his journey from boy to man--and Harry faces more danger than that found in all six books combined, from the direct threat of the Death Eaters and you-know-who, to the subtle perils of losing faith in himself. Attentive readers would do well to remember Dumbledore\'s warning about making the choice between ""what is right and what is easy,"" and know that Rowling applies the same difficult principle to the conclusion of her series. While fans will find the answers to hotly speculated questions about Dumbledore, Snape, and you-know-who, it is a testament to Rowling\'s skill as a storyteller that even the most astute and careful reader will be taken by surprise.

A spectacular finish to a phenomenal series, Harry Potter and the Deathly Hallows is a bittersweet read for fans. The journey is hard, filled with events both tragic and triumphant, the battlefield littered with the bodies of the dearest and despised, but the final chapter is as brilliant and blinding as a phoenix\'s flame, and fans and skeptics alike will emerge from the confines of the story with full but heavy hearts, giddy and grateful for the experience. --Daphne Durham"	', created_at: '	2017-06-20 13:07:00 UTC	', updated_at: '	2017-06-20 13:07:00 UTC	')
Post.create(name: '	J. R. R. Tolkien	', title: '	The Fellowship of the Ring	', body: '	"The first volume in J.R.R. Tolkien\'s epic adventure THE LORD OF THE RINGS
 
One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them

In ancient times the Rings of Power were crafted by the Elven-smiths, and Sauron, the Dark Lord, forged the One Ring, filling it with his own power so that he could rule all others. But the One Ring was taken from him, and though he sought it throughout Middle-earth, it remained lost to him. After many ages it fell into the hands of Bilbo Baggins, as told in The Hobbit. In a sleepy village in the Shire, young Frodo Baggins finds himself faced with an immense task, as his elderly cousin Bilbo entrusts the Ring to his care. Frodo must leave his home and make a perilous journey across Middle-earth to the Cracks of Doom, there to destroy the Ring and foil the Dark Lord in his evil purpose.

“A unique, wholly realized other world, evoked from deep in the well of Time, massively detailed, absorbingly entertaining, profound in meaning.” – New York Times"	', created_at: '	2017-06-21 13:01:00 UTC	', updated_at: '	2017-06-21 13:01:00 UTC	')
Post.create(name: '	J. R. R. Tolkien	', title: '	The Two Towers	', body: '	"The second volume in J.R.R. Tolkien\'s epic adventure THE LORD OF THE RINGS

One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them

Frodo and his Companions of the Ring have been beset by danger during their quest to prevent the Ruling Ring from falling into the hands of the Dark Lord by destroying it in the Cracks of Doom. They have lost the wizard, Gandalf, in a battle in the Mines of Moria. And Boromir, seduced by the power of the Ring, tried to seize it by force. While Frodo and Sam made their escape, the rest of the company was attacked by Orcs. Now they continue the journey alone down the great River Anduin—alone, that is, save for the mysterious creeping figure that follows wherever they go. 

“Among the greatest works of imaginative fiction of the twentieth century. The book presents us with the richest profusion of new lands and creatures, from the beauty of Lothlórien to the horror of Mordor.” – Sunday Telegraph"	', created_at: '	2017-06-21 13:02:00 UTC	', updated_at: '	2017-06-21 13:02:00 UTC	')
Post.create(name: '	J. R. R. Tolkien	', title: '	The Return of the King	', body: '	"The third volume in J.R.R. Tolkien\'s epic adventure THE LORD OF THE RINGS 

One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them

As the Shadow of Mordor grows across the land, the Companions of the Ring have become involved in separate adventures. Aragorn, revealed as the hidden heir of the ancient Kings of the West, has joined with the Riders of Rohan against the forces of Isengard, and takes part in the desperate victory of the Hornburg. Merry and Pippin, captured by Orcs, escape into Fangorn Forest and there encounter the Ents. Gandalf has miraculously returned and defeated the evil wizard, Saruman. Sam has left his master for dead after a battle with the giant spider, Shelob; but Frodo is still alive—now in the foul hands of the Orcs. And all the while the armies of the Dark Lord are massing as the One Ring draws ever nearer to the Cracks of Doom. 

“A triumphant close . . . a grand piece of work, grand in both conception and execution. An astonishing imaginative tour de force.” – Daily Telegraph

Includes the complete appendices and index for The Lord of the Rings trilogy."	', created_at: '	2017-06-21 13:03:00 UTC	', updated_at: '	2017-06-21 13:03:00 UTC	')
Post.create(name: '	B. B. Hiller	', title: '	The Karate Kid	', body: '	The Karate Kid	', created_at: '	2017-06-22 13:01:00 UTC	', updated_at: '	2017-06-22 13:01:00 UTC	')
Post.create(name: '	B. B. Hiller	', title: '	The Karate Kid, Part II	', body: '	If you loved the movie, then you will enjoy reading the book that continues the story after Daniel wins the tournament.	', created_at: '	2017-06-22 13:02:00 UTC	', updated_at: '	2017-06-22 13:02:00 UTC	')
Post.create(name: '	B. B. Hiller	', title: '	The Karate Kid Part III	', body: '	The Karate Kid Part III	', created_at: '	2017-06-22 13:03:00 UTC	', updated_at: '	2017-06-22 13:03:00 UTC	')
